description: "Перевод средств"

/transfer:
    post:
        securedBy: [ userAuth ]
        description: "Перевод средств"
        body:
            application/json:
                example: !include example/transfer-request.json
        responses:
            200:
                body:
                    application/json:
                        example: !include example/transfer-reponse.json
/issue:
    post:
        securedBy: [ userAuth ]
        description: "Эмиссия средств"
        body:
            application/json:
                example: !include example/issue-request.json
        responses:
            200:
                body:
                    application/json:
                        example: !include example/issue-reponse.json
