<?php

return [
    new \ZnSandbox\Sandbox\Apache\Bundle(['all']),
    new \ZnLib\Rpc\Bundle(['all']),
    new \ZnUser\Password\Bundle(['all']),
    new \ZnSandbox\Sandbox\Application\Bundle(['all']),
    new \ZnCrypt\Jwt\Bundle(['all']),
    //new \ZnBundle\Reference\Bundle(['all']),
//    new \ZnSandbox\Sandbox\Person\Bundle(['all']),
    new \ZnUser\Registration\Bundle(['all']),
    new \ZnSandbox\Sandbox\Geo\Bundle(['all']),
    new \ZnSandbox\Sandbox\Settings\Bundle(['all']),
    new \ZnBundle\Log\Bundle(['all']),
    new \ZnBundle\Storage\Bundle(['all']),
    new \ZnBundle\Dashboard\Bundle(['all']),
    new \ZnBundle\Notify\Bundle(['all']),
//    new \ZnBundle\Messenger\Bundle(['all']),
    new \ZnBundle\Language\BundleNew(['all']),
    new \ZnBundle\Summary\Bundle(['all']),
    new \ZnBundle\User\NewBundle(['all']),
    //new \ZnUser\Registration\Bundle(['all']),
    new \ZnBundle\Queue\Bundle(['all', 'console']),
    new \ZnSandbox\Sandbox\Layout\Bundle(['all']),
    new \ZnBundle\Person\Bundle(['all']),
    new \ZnBundle\Eav\Bundle(['all']),
    new \ZnUser\Rbac\Bundle(['all']),
    new \App\Common\Bundle(['all']),
//    new \App\Person\Bundle(['all']),
    new \ZnSandbox\Sandbox\Rpc\Bundle(['all']),
    new \ZnUser\Notify\Bundle(['all']),
    new \ZnSandbox\Sandbox\RpcClient\Bundle(['all']),
];
